// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITokenRecipient$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITokenRecipient";
  readonly sourceName: "contracts/4_ITokenRecipient.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"operator","type":"address"},{"internalType":"address","name":"from","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onTransferReceived","outputs":[{"internalType":"bytes4","name":"","type":"bytes4"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/4_ITokenRecipient.sol";
  readonly buildInfoId: "solc-0_8_28-559b143941ea993150ff5fdc64ba5142bcd63210";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITokenRecipient"]: ITokenRecipient$Type;
    ["contracts/4_ITokenRecipient.sol:ITokenRecipient"]: ITokenRecipient$Type;
  }
}