// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBank$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBank";
  readonly sourceName: "contracts/2_IBank.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/2_IBank.sol";
  readonly buildInfoId: "solc-0_8_28-559b143941ea993150ff5fdc64ba5142bcd63210";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBank"]: IBank$Type;
    ["contracts/2_IBank.sol:IBank"]: IBank$Type;
  }
}